do not jump away from initializing variables
gcc version 9.3.0 treats these as errors

from C++ standard:
It is possible to transfer into a block, but not in a way that bypasses
declarations with initialization. A program that jumps from a point
where a local variable with automatic storage duration is not in scope
to a point where it is in scope is ill-formed unless the variable has
POD type (3.9) and is declared without an initializer.

../src/diann.cpp: In member function ‘void Feature::find(bool, std::vector<Mass>&, std::vector<Mass>&, std::vector<std::pair<float, int> >&, double, double, std::vector<Match>&)’:
../src/diann.cpp:2583:4: error: jump to label ‘finish’
 2583 |    finish:
      |    ^~~~~~
../src/diann.cpp:2552:53: note:   from here
 2552 |     if (open && iter == 1 && pos->charge != 1) goto finish;
      |                                                     ^~~~~~
../src/diann.cpp:2553:11: note:   crosses initialization of ‘std::pair<float, int>& pr’
 2553 |     auto &pr = precursors[pos->pr];
      |           ^~

../src/diann.cpp: In member function ‘void Library::max_lfq_quant(std::vector<PG>*, std::vector<Lock>*, double, bool)’:
../src/diann.cpp:5443:4: error: jump to label ‘save’
 5443 |    save:
      |    ^~~~
../src/diann.cpp:5396:10: note:   from here
 5396 |     goto save;
      |          ^~~~
../src/diann.cpp:5399:8: note:   crosses initialization of ‘int ni’
 5399 |    int ni = indices.size();